### ISSUE TITLE
where i need write commands to sets the delay between each attempt?)

### ISSUE THREAD

**Issue by Feihuiy** [Bstn1802/AutoReconnect#10]
where i need write commands to sets the delay between each attempt?)

**Comment by zatrit** [comment]
Currently it's impossible, because mod have no config

**Comment by Bstn1802** [comment]
Actually it does have a config. At least it should. Also theres a command with which you can configure the mod in game. Just type it in the chat like every other command.
I assume youre not coming from the curseforge page, otherwise you wouldve written there, so if you download the mod there it should be the latest version in which i added that feature and i mightve actually forgotten to upload it here, ill check that right now
Also for the future, dont open issues for questions. Im pretty sure thats not the intended use for that. Ask questions on the curseforge page instead, ill link it in the readme, which btw should already answer your question, so i assume you didnt read it, which is a shame. If you actually did and it was unclear, then im sorry, and please tell me how to improve it to make it more understandable
