### ISSUE TITLE
Auto Message

### ISSUE THREAD

**Issue by StarMasterBM2** [Bstn1802/AutoReconnect#18]
Hi i recently needed a mod that auto reconnects and has a auto message feature this seemed perfect soo i downloaded it and it works but the only issue i have is that auto message does not work i tried it multiple times restarted minecraft re added messages but i couldn't fix it it doesn't  crash or anything like that i would like if i can get some help :D

**Comment by Bstn1802** [comment]
I'm not very happy with the current implementation, I have to admit xD
So I just needed a few tries myself to get it work on a local server. So you need to enter the address of the server which I think you are aware of, so my guess is that you need to enter the IP address and the url you might be trying to enter instead might not work.
So if you have something like `awesomeserver.minehut.net` or so, that might not work, but I'm not sure, since in my case, testing on a local server, entering `localhost` worked (`Localhost` did not btw). Otherwise you could try the IP which could look something like this `123.345.567.789:12345` and might have a port as well if it's not `25565` which is the default one. The other option would be to exactly copy paste the address you entered when adding the server to your multiplayer menu, it might be the case that that's the one which it will compare against, but I'm not quite sure honestly :'D
Good news: The mod will be getting a big update and I will probably improve this as well :D

**Comment by Bstn1802** [comment]
I improved this feature with the latest release. Now you need to enter the name of the server/realm entry in the menu or the name of the singleplayer world. Those should be unique since you can set them yourself, exception being realms, but what are the odds that you have two realms with the same name.
You can still only configure one instance, I kinda wanted to change that, but I didn't have the time now, so that's to be changed in the future.

**Comment by joex92** [comment]
> I improved this feature with the latest release. Now you need to enter the name of the server/realm entry in the menu or the name of the singleplayer world. Those should be unique since you can set them yourself, exception being realms, but what are the odds that you have two realms with the same name. You can still only configure one instance, I kinda wanted to change that, but I didn't have the time now, so that's to be changed in the future.

Hi, what about using `*` for any server? that way I don't have to change it everytime I play in other servers, that way the mod should use the last disconnected server name, right?

**Comment by Bstn1802** [comment]
I might consider this for the next update

PS: Usually you'd open a new issue for that, but it's okay, you don't need to know, I just wont open this issue again, your request is noted

**Comment by joex92** [comment]
> I might consider this for the next update
> 
> PS: Usually you'd open a new issue for that, but it's okay, you don't need to know, I just wont open this issue again, your request is noted

oh, sorry, I thought it would be ok because it was kinda the same topic... 😅 
but thanks
