### ISSUE TITLE
Crashing at starting

### ISSUE THREAD

**Issue by TheButterbrotMan** [Bstn1802/AutoReconnect#19]
https://bytebin.lucko.me/buLN7ZEVSY <- Clientcrashlog

**Comment by Bstn1802** [comment]
First of all, I don't know why you mentioned me in those other issues, those are both server side. I don't have anything to do with those errors and those two mods don't have anything to do with the error in the client crash report.
Second, I don't really know why this error is happening, I know what's causing it and I could prevent it from happening, but I don't know how this error could occur in the first place, like my mod seems to be capturing changes in the ui even before it is loaded and therefore can't do the things it's supposed to do, since it's not loaded yet, but why is it capturing those changes in the ui already then? Weird stuff, I'll try to investigate further, but it would be really helpful if you could narrow down the possibilities of what is causing it. You really have a heavly modded setup there and although there's no mention of any other mod causing the error in the crash report I think there might be some other cause for this error. After all, minecraft doesn't crash for me and I'm pretty sure someone else would've told me already if it did for them. So I suggest you try starting minecraft only with autoreconnect and clothconfig first, see if that crashes too and if not then you could maybe try figure out what mod might be indirectly causing it.

**Comment by TheButterbrotMan** [comment]
I mentioned you there, because when client crashes a client and server crashlog get generated. So I was not sure, if it is caused by the both server mods or your client mod.

**Comment by TheButterbrotMan** [comment]
It could be that server crashes, and then client does also. So maybe there's nothing wrong, and your mod is fine. Or your mod is the cause. IDK. So i linked all reports together.

**Comment by Bstn1802** [comment]
The other two issues have something to do with the LanternBlock they're extending, I can definitely not cause that. It sounds very reasonable that the server crash is causing the client crash, although it's weird that fabric is differentiating so much, since it's both in the client game and not a literal server. Right?
Would be great if you could confirm that minecraft is only crashing when at least one of those two mods are present and it's working of they're both not.
