### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by TechPro424** [Bstn1802/AutoReconnect#24]

**Comment by Bstn1802** [comment]
I've updated local changes (I've been working on new features) to 1.19 already, but I'm still trying to fix some bugs, get rid of some open issues here. I planned to release the update this week, but it might take a bit longer.

**Comment by TechPro424** [comment]
Any progress?

**Comment by Bstn1802** [comment]
Sorry that it took that long. As I said, I had new features prepared that I wanted to release, the update for 1.19 would've been so simple otherwise, but together with those features and that one bug fix it was kind of a mess. Still missing one feature and I'm waiting for a pullrequest to be updated, but that's why this release is a beta. I hope I can bring the full release next week.

**Comment by TechPro424** [comment]
Take your time, no issues :)
