### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by Sunconure11** [Bstn1802/AutoReconnect#27]
https://pastebin.com/KjnR5cdQ

**Comment by Bstn1802** [comment]
Looks similar to #20 which should be fixed with the latest release, although the author of that issue hasn't confirmed that yet and you're probably playing on 1.18.2 for a reason, but with 1.19 being released by now I'm targeting that version
If it is that issue, you should only get it when creating a world tho, at least that's when the author of the other issue got that error, but then you should be fine once it's been created, otherwise, can you tell me when did you get the error?

**Comment by Sunconure11** [comment]
After creation of a world. I think the issue was something else entirely though
