### ISSUE TITLE
bogs my 12700k and crashes

### ISSUE THREAD

**Issue by Reekid3** [Bstn1802/AutoReconnect#32]
I press open Minecraft or whatever cpu gose 2 100 percent and it crashes this is the first time a game has ever capped my cpu that usually goes to blender

**Comment by Reekid3** [comment]
I thought I got it working today but actually just goofed up and forgot to install the actual mod just had everything else

**Comment by Bstn1802** [comment]
Can't help you with that, I need more information. Best you send the crash report, preferably by using something like pastebin or I think attaching files is a thing now too here

**Comment by Reekid3** [comment]
do you htink it could be a problem with 12th gen intel cpus

**Comment by Bstn1802** [comment]
very unlikely, as I said, it's best if you send the crash report, then I can look into it and figure out what is causing the crash

**Comment by Reekid3** [comment]
I dont know how to get logs from fabric

**Comment by Bstn1802** [comment]
If the game crashes you should get a popup where you can say "open crash report". Otherwise you can find the log files in the "logs" folder in you game profile folder, which could be the minecraft folder itself or one inside depending how you've set everything up, but you should know how to get there, because you should know how to get to the "mods" folder and the "logs" folder is in the same folder as the "mods" folder is in. Unless you use a launcher that does all that for you but that should also have an option to open the "mods" folder for you I guess, at least the main launcher has it. Otherwise just find it yourself, look up how to get there online.

**Comment by Reekid3** [comment]
[2022-08-25-2.log.gz](https://github.com/Bstn1802/AutoReconnect/files/9436983/2022-08-25-2.log.gz)
wow I thought I was gonna have 2 upload 2 drives and give you link this is so much easier dose this help ?? or is it just chat history like the file latest.log

**Comment by Bstn1802** [comment]
Okay, no, if your game crashes, as you claimed, then I actually need the crash report. You shuold be able to reproduce that and as I said then there'll be a popup where you can choose "open crash report" or maybe you can find them in the log folder too, I'm not quite sure right now.
The log file I thought could help too, but it mainly shows chat history, yes, and some logs from different mods and minecraft itself, although from the logs I can tell that you're not even using modded, you're just using Optifine, or lets say I highly doubt you're using mods, or have been using mods in that session, since there's no trace of fabric, my mod or any other mod really.

**Comment by Reekid3** [comment]
ssry I just grabbed the most recent log I was assuming it would be the last crash log Ive been using opt fine here leme get it 

all I got was a exit code wich was "1" 

when I opened it and it chrashed it added a log file heres that
[2022-08-27-2.log.gz](https://github.com/Bstn1802/AutoReconnect/files/9438038/2022-08-27-2.log.gz)

**Comment by Bstn1802** [comment]
Yes that's the one, thanks. It seems like my mod just doesn't work for 1.19.2. It's definitely my mod causing the crash, you're using the latest version of it, and the errors in the crash report look like there have been some changes from 1.19 to 1.19.2 which affect my mod. I myself am not using 1.19+ because of all the chat reporting stuff, not sure if I really want to support those versions or make versions of my mod for both 1.19 and 1.19.2. I'll have to think about it, but I think with that this issue is closed at least and again, I can't tell you if or when I'll make an update for 1.19.2, but if I do you will definitely see it on the curseforge page and probably here too.

**Comment by Reekid3** [comment]
so what do you recommend
