### ISSUE TITLE
Mark mod on CurseForge as 1.19.2

### ISSUE THREAD

**Issue by TechPro424** [Bstn1802/AutoReconnect#33]
Please mark the mod on CurseForge as 1.19.2 compatible so I can use launchers like PolyMC to install and update it

**Comment by Mshangao** [comment]
You can try install mod manually. Most launchers allow us to do it (sorry for my english)

**Comment by TechPro424** [comment]
Yes, but its more convenient to have auto-update

**Comment by Mshangao** [comment]
Ye, but for me it's more important to make auto messages working correct than auto update mod if we can do it manually. If you're on server with multiple game types then it's easier if mod will automatically connect you with for example /survival or /skyblock /pvp

Easier, better, more convinient

**Comment by TechPro424** [comment]
This is not something to be done in the code
He just has to go to CF and mark the mod as 1.19.2

**Comment by Bstn1802** [comment]
I marked it as beta I think, that's probably why it doesn't auto update. Kinda did that for a reason, but it sounds annoying indeed and I'm not currently working on the mod either, so no release in sight that could replace the beta version, I think imma change it from beta to release to fix it.
...actually it's just 1.19, never updated it to 1.19+ with all the chat report stuff, still playing 1.19 myself. Is it even compatible with 1.19.2? I mean I guess so, but I've never tested it.

**Comment by Mshangao** [comment]
Yes, it is compatible with 1.19.2, I'm using it everyday, but feature called AutoMessages is more dead than Wither after he drops his star. It is really important feature that will help a lot of users I think, so I would like to see it working :|

**Comment by Bstn1802** [comment]
AutoMessages should be working ...if that's not due to the fact that I technically didn't update the mod for 1.19+. Is there anything suspicious in the log files? If so, could you (or someone) post one here? (There's chat massages in there, so it's better for both of us (privacy reasons for you/lot of content to skip for me) if it's a log file of a quick session where you just rejoin a couple times maybe)
...wait, are you using mod version 2.1.0-beta for 1.19? Because version 2.0.0 for 1.18.2 was working for 1.19 but AutoMessages was broken, I just remembered that, so try the new version if you're not using that and forget what I said before if that fixes it xD

**Comment by Mshangao** [comment]
I have it configured like that:
![image](https://user-images.githubusercontent.com/107376720/203179583-99507333-10c6-44b3-8635-7776b6193337.png)

And yes, I'm using latest, 2.1.0-beta version for 1.19

Server where I play has simply build. When you join you can type /survival press enter and Tadaa! You joined survival world!

I tested it milion times, but this command is not pasted, did in game. Nah, it's not typing any other message

I can join only while using Macro Commands while repeating this same command over and over again, but it's making a lot of spam in console and owner of server where I play is annoyed because of it.

Can you check this out? Maybe I'm doing something wrong.
If something, I'm playing on NetherCat.tk, but I think that you can't join from other country than Poland/Germany, but 1. you can try 2. owner can add you to whitelist 3. you can tell your country and I will ask him to unlock it
Ofc if you have Minecraft Premium, if not it's bit more complicated, but I'll tell you later, if you wanna join and test ^^

I'll be really glad if you will help me with it, because I think that your mod is really useful, simply and light. Perfect combination. And also unique, you're only one that developed such thing O.O

**Comment by Bstn1802** [comment]
Oh I see, the "name" of the AutoMessages object must be the name of the singleplayer world, multiplayer server or realm you want this to work on. It's not meant to be an arbitrary name for the object itself. The tooltip for that entry has more information, but to be fair the name could be more descriptive as well.
So whatever this server is called in the list of servers you have in the menu, that is what needs to go in that textfield.

**Comment by Bstn1802** [comment]
Since thats most likely the issue and you said it's working for 1.19.2, I marked it 1.19.2 compatible and even made the bold assumption that it does for 1.19.3 too, which apparently got released in the meantime, totally missed that, but I think not much has changed so it should be fine.
