### ISSUE TITLE
Switch to LGPL 3.0 license

### ISSUE THREAD

**Issue by TechPro424** [Bstn1802/AutoReconnect#42]
This mod is licensed under GPL-3.0. While this is usually a good thing, in the case of a Minecraft mod it actually restricts the freedom of users due to the linking restrictions (this is why the Quilt template mod default README states that it is incompatible).

Another source is Modrinth's licensing guide: https://blog.modrinth.com/p/licensing-guide
Check the "Copyleft license" section

None of this is legal advice, just information that I have seen/received from other sources
No warranty is given regarding this information, and I (TechPro424) disclaim liability for damages resulting in using this information given on an "as-is" basis.

**Comment by Bstn1802** [comment]
Thanks for the suggestion. I was looking into that guide back when you posted it, but couldn't figure out how to properly change the license here, since github doesn't have a template for that licence. Now I got it from https://www.gnu.org/licenses/lgpl-3.0.md and I think that's fine, github recognizes it fine.
