### ISSUE TITLE
autoreconnect-2.2.0:  Can't reconect message if connecting with command line --server --port

### ISSUE THREAD

**Issue by cunhar** [Bstn1802/AutoReconnect#56]
examples from portable mc:
https://github.com/mindstorm38/portablemc/issues/153

**Comment by Bstn1802** [comment]
This should already be fixed with issue #54. I think it's not in the latest release yet, since I've been working on another feature I wanted to release together with that fix as I thought it was no major issue.
I'm not sure if the arguments --server and --port will work tho, since they got replaced by the quickPlay arguments in 1.20. Depending on how they're implemented in portablemc, which I don't know anything about, I only just read something about retro-compatibility, so I assume they implemented them back, but as I was saying, depending on how they implemented them back, it may or may not work. I'm pretty confident tho that it should, since I carefully picked a new point in minecrafts code to inject mine into to register even connection attempts that didn't go through the gui.
I'll attach a build of the current code on github here which already includes that fix and it would be great if you could test your scenario with that.
[autoreconnect-2.3.0-dev.zip](https://github.com/Bstn1802/AutoReconnect/files/12327185/autoreconnect-2.3.0-dev.zip)

**Comment by cunhar** [comment]
@Bstn1802 could you hook me up with a JAR

**Comment by Bstn1802** [comment]
That's a jar, forgot to give more instructions, so basically GitHub doesn't allow upload of .jar files etc. because they could be harmful and what not, so I just renamed it into .zip instead. You can just drop that into the mod folder, might not even need to rename it, but I'm not sure, maybe rename it to .jar to be sure.

**Comment by cunhar** [comment]
@Bstn1802 thank you <3

**Comment by cunhar** [comment]
@Bstn1802 --- i just tested it and it works great!  Thanks again for being a core piece of what keeps my 24 hour minecraft stream possible

**Comment by Bstn1802** [comment]
No problem, glad to hear it works and that this mod genuinely helps you :)
Closing this then, as it's resolved
