### ISSUE TITLE
[feature request] command when rejoining

### ISSUE THREAD

**Issue by TheCrandall** [Bstn1802/AutoReconnect#64]
I think its a good way to join the lobby servers.

**Comment by Bstn1802** [comment]
Already a thing, just use the AutoMessages feature and type the command with a slash in front as you would in chat and that will be recognized so that the text will be sent as a command instead of a message.
You'll find this in the config under auto messages, add an entry there and type in the name of the server you want to use it on, the messages you want to be sent and the delay in milliseconds it should take before sending each message.
This should work at least until the latest known supported version, meaning 1.20.1, but still might work for 1.20.4, I'm not sure, haven't gotten to upgrade it since then.
Closing this as this is not a new feature request, fell free to answer tho when you have further questions.
