### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by AidsterGaming** [Bstn1802/AutoReconnect#9]
Can't change the time it takes to reconnect, changing the config file does nothing.
Also if possible can the config be updated to work with the [Mod Menu mod](https://www.curseforge.com/minecraft/mc-mods/modmenu) UI.
Thanks in advance.

**Comment by Bstn1802** [comment]
You dont need to manually change the config file. Use the command instead. If you do change it manually and the game is open, you need to reload the config with the command or theoretically you could restart the game but why would you want to.

**Comment by Bstn1802** [comment]
And talking about the Mod Menu Mod. As far as i know it only allows you to create a link to an already existing config ui which this mod doesn't have. I would need to use a library to make one, which is not worth it because it's just a single property, namely the list of intervals and because it's a list it is a very complex property type. You can not just use a button, a slider or a textfield which most other mods use in their config and i dont know if it would be easy to design a ui with the existing libraries out there. I could also make a ui myself, but thats too much effort in my opinion for a simple list of integers which can be easily set using the command.
